### ISSUE TITLE
[Bug]: [CAT] Linux window controls overlap with action buttons

### ISSUE THREAD

**Issue by dumbmoron** [imputnet/helium#441]
### Operating system

Linux

### Version

main

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in Helium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Window controls are overlapping with action buttons in CAT mode

### How to Reproduce?

Open Helium in xfce4 with CAT enabled

### Actual behavior

<img width="1280" height="214" alt="Image" src="https://github.com/user-attachments/assets/99adf384-3a8a-441d-97fc-98cad537bc21" />

### Expected behavior

no overlap

**Comment by vpsone** [comment]
Same issue in fedora 43 kde

<img width="1920" height="250" alt="Image" src="https://github.com/user-attachments/assets/f12ed039-6a28-4800-96bb-55eb4dea70ea" />

**Comment by vmx2f** [comment]
Same issue on windows if the window is too small 

<img width="492" height="170" alt="Image" src="https://github.com/user-attachments/assets/e2694c5f-e84c-4877-9c79-bbe5d7ea1720" />

**Comment by wukko** [comment]
can you guys check if this still happens to you on latest builds?

**Comment by vpsone** [comment]
It's fixed in fedora 43 kde.
<img width="1920" height="101" alt="Image" src="https://github.com/user-attachments/assets/f302ea31-44b2-40d4-a242-1ed093945b22" />

**Comment by vmx2f** [comment]
Still happens on windows 
<img width="504" height="373" alt="Image" src="https://github.com/user-attachments/assets/c134b1aa-0047-47b6-b5e3-e9d744124e48" />
